-- =============================================================================
-- 89_restore_select_on_profiles_id.sql
-- 把 profiles.id 的 SELECT 授权还回去 —— 否则**注册走不完**
--
-- ── 症状 ─────────────────────────────────────────────────────────────────────
-- 新用户注册后填完资料保存失败，卡在 onboarding 出不去。
-- 同样受影响的还有编辑资料、换头像、改通知开关 —— 一切写 profiles 的路径。
--
-- ── 根因 ─────────────────────────────────────────────────────────────────────
-- 迁移 79 逐列撤销了 SELECT。但客户端保存资料是这么写的：
--
--     from('profiles').update(fields).eq('id', user.id)
--
-- **Postgres 里 UPDATE ... WHERE 也需要 WHERE 引用列的 SELECT 权限。**
-- 我当时只想着「读不到 = 查不到 PII」，没想到写也要读一下 id。
-- 数据库的报错其实说得很清楚：
--     ERROR: 42501 permission denied for table profiles
--     HINT:  GRANT SELECT ON public.profiles TO authenticated;
--
-- ── 修法 ─────────────────────────────────────────────────────────────────────
-- 只把 `id` 一列还回去。**不要整表 grant**。
--
-- 只放 id 不会泄露任何东西：
--   · 策略已经是「只看自己那一行」（迁移 79），能 select 到的 id 只有 auth.uid()
--   · 别人的 id 本来就从各处 RPC 正常返回（好友列表、群成员等）
--   · 真正敏感的 date_of_birth / personal_email / edu_email / pet_name 等
--     仍然一列都读不到，裸形态匿名规则不受影响
--
-- 更彻底的做法是把资料写入也改成 SECURITY DEFINER RPC（跟本项目其它写路径一致），
-- 那样连这一列授权都不需要。留作后续，先解开注册。
--
-- 回滚：db-backups/2026-08-15/ROLLBACK_89.sql
-- =============================================================================

grant select (id) on public.profiles to authenticated;
